title: Roblox Scripting Assistance - Resources
invite_link: https://discord.com/invite/FCmRaM42EV

source: ./pages/source
destination: ./pages/build

url: https://pogchonk.github.io/RSA-R_TestRepo
git: https://github.com/PogChonk/RSA-R_TestRepo

markdown: kramdown
kramdown:
  header_offset: 2
  syntax_highlighter_opts:
    disable: true
plugins:
  - jekyll-archives
  - jekyll-autoprefixer

jekyll-archives:
  enabled:
    - year
    - month
    - categories
  layouts:
    year: archive-year
    month: archive-month
    category: archive-category
  permalinks:
    year: "year/:year/"
    month: "year/:year/month/:month/"
    category: "/category/:name/"
